### PR TITLE
Overhaul SymbolLoader

### LINKED ISSUE #273: NativeScript::SymbolLoader incorrectly caches framework bundles
Reported by @Fatme:

```
<Notice>: /app/tns_modules/location/location.js:56:52: JS ERROR ReferenceError: Can't find variable: kCLDistanceFilterNone
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 1   0x10007ac3c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif, void, void*, void)
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 2   0x1004fab24 ffi_closure_SYSV_inner
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 3   0x1004fb1b4 .Ldo_closure
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 4   0x18a7cbf08 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 5   0x18a86a544 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 6   0x18a869f30 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 7   0x18a869c50 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 8   0x18a869bd0 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 9   0x18a7b16f4 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 10  0x18a0eddb8 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 11  0x18a0e8820 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 12  0x18a0e86c4 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 13  0x18a0e7e58 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 14  0x18a0e7bd8 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 15  0x18aa407cc <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 17  0x18aa3f70c <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 19  0x185cf427c <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 20  0x185cf3384 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 21  0x185cf19a8 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 22  0x185c1d2d4 CFRunLoopRunSpecific
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 23  0x18a8203d0 <redacted>
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 24  0x18a81af40 UIApplicationMain
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 25  0x1004fb044 ffi_call_SYSV
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 26  0x1004fa334 ffi_call_int
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 27  0x10004f71c NativeScript::FFIFunctionCall::derivedExecuteCall(JSC::ExecState, unsigned char)
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 28  0x10004f8e4 long long NativeScript::FFICall::executeCall<NativeScript::FFIFunctionCall>(JSC::ExecState*)
Aug 19 15:46:13 Georgi-Alexandrovs-iPhone sampleFriends[6373] <Notice>: 29  0x1002f9acc JSC::LLInt::setUpCall(JSC::ExecState, JSC::Instruction, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
```

### PR DESCRIPTION
**Pull request by fealebenpae**
Make SymbolLoader cache by the ModuleMeta pointer, which is unique.
SymbolLoader now supports embedded frameworks.
Stubbed support for dylibs.

Fixes #273

### CODE REVIEW

File: src/NativeScript/SymbolLoader.mm [hunk 1]
```diff
@@ -6,75 +6,146 @@
...
-                         isDirectory:YES];
+            NSBundle* foundation = [NSBundle bundleForClass:[NSString class]];
+            NSString* foundationPath = [foundation bundlePath];
+            NSString* basePathStr = [foundationPath substringToIndex:[foundationPath rangeOfString:@"Foundation.framework"].location];
+            baseUrl = [NSURL fileURLWithPath:basePathStr isDirectory:YES];
+#else
+            baseUrl = [NSURL fileURLWithPath:@"/System/Library/Frameworks" isDirectory:YES];
 #endif
+        } else {
+            baseUrl = [[NSBundle mainBundle] privateFrameworksURL];
```
Comment (jasssonpet) [inline src/NativeScript/SymbolLoader.mm]: Can you share some frameworks that would need this? I'm just wondering how this is helpful, because I don't remember having anything similar before.

Comment (fealebenpae) [inline src/NativeScript/SymbolLoader.mm]: This is supposed to handle embedded frameworks that export functions and other symbols. They've worked up to now, yes, but they've relied on the `RTLD_GLOBAL` fallback.

File: src/NativeScript/SymbolLoader.mm [hunk 2]
```diff
@@ -6,75 +6,146 @@
 //  Copyright (c) 2014 г. Telerik. All rights reserved.
```
Comment (jasssonpet) [inline src/NativeScript/SymbolLoader.mm]: You could also rename the header from `SymbolLoader.cpp` to `SymbolLoader.mm` if you want :D

File: src/NativeScript/SymbolLoader.mm [hunk 3]
```diff
@@ -6,75 +6,146 @@
...
 
-    NSURL* bundleUrl = [NSURL URLWithString:frameworkPathStr
-                              relativeToURL:baseUrl];
-    WTF::RetainPtr<CFBundleRef> bundle = adoptCF(CFBundleCreate(kCFAllocatorDefault, (CFURLRef)bundleUrl));
-    cache.insert(std::make_pair(frameworkName, bundle));
-    return bundle.get();
-}
+        NSURL* bundleUrl = [NSURL URLWithString:frameworkPathStr relativeToURL:baseUrl];
+        WTF::RetainPtr<CFBundleRef> bundle = adoptCF(CFBundleCreate(kCFAllocatorDefault, (CFURLRef)bundleUrl));
+        WTF::dataLogF("NativeScript loaded bundle %s", bundleUrl.absoluteString.UTF8String);
```
Comment (jasssonpet) [inline src/NativeScript/SymbolLoader.mm]: You could append '\n' at the end.

**Comment by jasssonpet** [comment]
This branch seems to crash on our tests when a the `CFBundle` is `nil` sometimes.

**Comment by fealebenpae** [comment]
Accelerate and Metal report themselves as non-system frameworks so this failed the isSystem check and resulted in paths to bundles that aren't there. I've added nil guards for `CFBundleCreate`.

**Comment by jasssonpet** [comment]
:+1:
